name: Find Work Package Overview Boards

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Find Boards
        run: |
          curl -X POST https://api.monday.com/v2 \
          -H "Authorization: ${{ secrets.MONDAY_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{"query":"{ boards(limit: 500) { id name workspace { id name } } }"}'
