name: Get Column Names

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Get Columns
        run: |
          curl -X POST https://api.monday.com/v2 \
          -H "Authorization: ${{ secrets.MONDAY_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{"query":"{ boards(ids: 5057678016) { columns { id title type } } }"}'
